export const LOGIN = 'LOGIN_USER';
export const LOGOUT = 'LOGOUT_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// Errors
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR';